package com.resolion.crm.enums;

public enum CampaignType {
    NONE,
    RESOLION_CAMPAIGNS,
    EMAIL_CAMPAIGN,
    SOCIAL_MEDIA,
    GOOGLE_ADS,
    FACEBOOK_ADS,
    LINKEDIN_ADS,
    WHATSAPP_CAMPAIGN,
    SMS_CAMPAIGN,
    WEBINAR,
    SURVEY,
    EVENT,
    TRADE_SHOW,
    REFERRAL,
    PRODUCT_LAUNCH,
    LEAD_GENERATION,
    BRAND_AWARENESS,
    CUSTOMER_RETENTION,
    OTHER
}