package com.resolion.crm.ENUMS;

public enum CaseReason {

    USER_DID_NOT_ATTEND_TRAINING,
    COMPLEX_FUNCTIONALITY,
    EXISTING_PROBLEM,
    INSTRUCTIONS_NOT_CLEAR,
    NEW_PROBLEM,
    PRODUCT_DEFECT,
    BILLING_ISSUE,
    FEATURE_GAP,
    CONFIGURATION_ISSUE,
    INTEGRATION_ISSUE,
    PERFORMANCE_ISSUE,
    SECURITY_ISSUE,
    OTHER
}