package com.resolion.crm.enums;

public enum DealLeadSource {
    NONE,
    ADVERTISEMENT,
    COLD_CALL,
    EMPLOYEE_REFERRAL,
    EXTERNAL_REFERRAL,
    ONLINE_STORE,
    PARTNER,
    PUBLIC_RELATIONS,
    SALES_EMAIL_ALIAS,
    SEMINAR_PARTNER,
    INTERNAL_SEMINAR,
    TRADE_SHOW,
    WEB_DOWNLOAD,
    WEB_RESEARCH,
    CHAT
}
