package com.resolion.crm.ENUMS;

public enum VendorGlAccount {
    NONE,
    SALES_SOFTWARE,
    SALES_HARDWARE,
    RENTAL_INCOME,
    INTEREST_INCOME,
    SALES_SOFTWARE_SUPPORT,
    SALES_OTHER,
    INTEREST_SALES,
    LABOR_HARDWARE_SERVICE,
    PURCHASES,
    COST_OF_GOODS_SOLD,
    PROFESSIONAL_SERVICES,
    CONSULTING_SERVICES,
    OTHER
}
